version: '3.8'

services:
  app:
    build: .
    container_name: diversion-vigan-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./server_data.json:/app/server_data.json
